fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
#    user_class: Sonata\UserBundle\Entity\BaseUser
#    user_class: App\Application\Sonata\UserBundle\Entity\User
    from_email:
        address: "oussema"
        sender_name: "oussema"
    group:
#        group_class:   Sonata\UserBundle\Entity\BaseGroup
#        group_class:   App\Application\Sonata\UserBundle\Entity\Group
        group_class:   App\Entity\Group
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager
